name = "InfinityReborn"
author = "MorenRx"
version = "3.0-A6(1.20.1)"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3670fbbe0af3093b97f94958f1cf25c2a8eefa1963e0bd34bc77e18cb7dd07fd"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
