name = "InfinityReborn"
author = "MorenRx"
version = "3.0-Alpha3(1.20.1)"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd2eb9c5f8d0f37070f99be6f3ab8cad471af18cafb5073e70a1ed965fb33c16"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
