const tieredText = {
	'tiered:weapon_star_1': Text.translate('infinity.tiered.1'),
    'tiered:weapon_star_2': Text.translate('infinity.tiered.2'),
    'tiered:weapon_star_3': Text.translate('infinity.tiered.3'),
    'tiered:weapon_star_4': Text.translate('infinity.tiered.4'),
    'tiered:weapon_star_5': Text.translate('infinity.tiered.5'),
	'tiered:armor_star_1': Text.translate('infinity.tiered.1'),
    'tiered:armor_star_2': Text.translate('infinity.tiered.2'),
    'tiered:armor_star_3': Text.translate('infinity.tiered.3'),
    'tiered:armor_star_4': Text.translate('infinity.tiered.4'),
    'tiered:helmet_star_5': Text.translate('infinity.tiered.5'),
    'tiered:chestplate_star_5': Text.translate('infinity.tiered.5'),
    'tiered:leggings_star_5': Text.translate('infinity.tiered.5'),
    'tiered:boots_star_5': Text.translate('infinity.tiered.5'),
	'tiered:ranged_star_1': Text.translate('infinity.tiered.1'),
	'tiered:ranged_star_2': Text.translate('infinity.tiered.2'),
	'tiered:ranged_star_3': Text.translate('infinity.tiered.3'),
	'tiered:ranged_star_4': Text.translate('infinity.tiered.4'),
	'tiered:ranged_star_5': Text.translate('infinity.tiered.5'),
	'tiered:ranged_star_6': Text.translate('infinity.tiered.5'),
	'tiered:ranged_heavy_star_2': Text.translate('infinity.tiered.2'),
	'tiered:ranged_heavy_star_3': Text.translate('infinity.tiered.3'),
	'tiered:ranged_heavy_star_4': Text.translate('infinity.tiered.4'),
	'tiered:ranged_heavy_star_5': Text.translate('infinity.tiered.5'),
	'tiered:mu_jian': Text.translate('infinity.tiered.hide')
}